# Funding configuration removed for this fork
# This is a personal fork of the original MyBrain project
# Original project: https://github.com/mhss1/MyBrain
# No funding is currently configured for this fork
